# Generated by Django 4.0.6 on 2022-08-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fnum', models.IntegerField()),
                ('lnum', models.BigIntegerField()),
                ('timestemp', models.DateTimeField()),
            ],
            options={
                'db_table': 'prim_num',
            },
        ),
    ]
