# Generated by Django 4.0.6 on 2022-08-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prime',
            name='timestemp',
        ),
        migrations.AlterField(
            model_name='prime',
            name='fnum',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prime',
            name='lnum',
            field=models.CharField(max_length=50),
        ),
    ]
